language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --exclude=libs,static --ignore=W191 ."
script:
  - ./manage.py test activities health
